const { Router } = require('express')
const multer = require('multer')
const multerConfig = require('./config/multer')
const UserController = require('./app/controllers/UserController')
const AlbumController = require('./app/controllers/AlbumController')
const MusicController = require('./app/controllers/SongController')
const SessionController = require('./app/controllers/SessionController')
const authMiddleware = require('./app/middlewares/auth')
const UsersController = require('./app/controllers/UsersController')
const UserAlbums = require('./app/controllers/UserAlbumController')
const SongController = require('./app/controllers/SongController')
const auth = require('./app/middlewares/auth')
const UserAlbumController = require('./app/controllers/UserAlbumController')

const upload = multer(multerConfig)
const routes = Router()

routes.post('/user', upload.single('file'), UserController.store)
routes.put('/user', authMiddleware, upload.single('file'), UserController.update)
routes.post('/album', upload.single('file'), AlbumController.store)
routes.post('/music', upload.single('file'), MusicController.store)
routes.post('/session', SessionController.store)
routes.get('/user', authMiddleware, UserController.show)
routes.get('/album', authMiddleware, AlbumController.index)
routes.get('/users', authMiddleware, UsersController.index)
routes.post('/setAlbumUser', authMiddleware, UserAlbums.store)
routes.get('/UserAlbums', authMiddleware, UserAlbums.index)
routes.post('/search/album', authMiddleware, AlbumController.show)
routes.post('/search/user', authMiddleware, UsersController.show)
routes.post('/song', authMiddleware, upload.single('file'), SongController.store)
routes.get('/song', authMiddleware, SongController.show)
routes.post('/album/delete', authMiddleware, UserAlbumController.delete)
routes.delete('/song/:id', authMiddleware, SongController.delete)

module.exports = routes